<a href="https://colab.research.google.com/github/swopnimghimire-123123/Data_Analysis_-_Visualization/blob/main/01_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Basic array creation

In [ ]:
import numpy as np
# Import the numpy library, commonly used for numerical operations.

In [ ]:
# Create a NumPy array from a Python list
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
# Create a Python list with mixed data types
a = [1,2,3,"Hello"]
a

[1, 2, 3, 'Hello']

In [ ]:
# Convert a Python list with mixed data types to a NumPy array
# Note that NumPy converts all elements to strings in this case
np.array(a)

array(['1', '2', '3', 'Hello'], dtype='<U21')

In [ ]:
# Create a nested Python list representing a 2D structure
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# Convert a nested Python list to a 2D NumPy array
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array generation function

In [ ]:
# Create a NumPy array with a range of values using np.arange()
# The array starts at 1, ends before 11, and steps by 2
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
# Create a 6x6 NumPy array filled with zeros
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# Create a 2x5 NumPy array filled with zeros
arr = np.zeros((2,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Create a 6x6 NumPy array filled with ones
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Create a NumPy array with values evenly spaced between 1 and 5
arr = np.linspace(1,5,2)
print(arr)
# Create another NumPy array with values evenly spaced between 1 and 20
brr = np.linspace(1,20,3)
print(brr)

[1. 5.]
[ 1.  10.5 20. ]


### Random Generation Function

In [ ]:
# Generate an array of 10 random numbers from a uniform distribution between 0 and 1
np.random.rand(10)

array([0.75381237, 0.44248055, 0.92523273, 0.76517273, 0.97457242,
       0.94840535, 0.90833291, 0.32633655, 0.4477448 , 0.67186202])

In [ ]:
# Generate an array of 10 random numbers from a standard normal distribution (mean 0, variance 1)
np.random.randn(10)

array([-0.04909868,  1.31130459, -1.01188257,  1.22143369, -1.82141515,
        0.72839214, -0.15311882,  0.01708684,  1.17318262,  0.20425348])

In [ ]:
# Generate an array of 9 random integers between 10 (inclusive) and 20 (exclusive)
np.random.randint(10,20,9)

array([18, 17, 16, 13, 15, 13, 18, 19, 11])

### Array Attributes

In [ ]:
# Create a 3x3 NumPy array
crr = np.array([[1,2,4],[4,5,6],[4,67,2]])
# Display the array
crr

array([[ 1,  2,  4],
       [ 4,  5,  6],
       [ 4, 67,  2]])

In [ ]:
# Get the shape of the array (rows, columns)
crr.shape

(3, 3)

In [ ]:
# Get the total number of elements in the array
crr.size

9

In [ ]:
# Get the data type of the elements in the array
crr.dtype

dtype('int64')

### Array Methods

In [ ]:
# Display the array again for reference
arr

array([1., 5.])

In [ ]:
# Find the minimum value in the array
arr.min()

np.float64(1.0)

In [ ]:
# Find the maximum value in the array
arr.max()

np.float64(5.0)

In [ ]:
# Calculate the sum of all elements in the array
arr.sum()

np.float64(6.0)

In [ ]:
# Calculate the sum of elements along axis 0 (columns) for the array 'arr'
# Note: This likely refers to a previous 'arr' which was a 2D array.
np.sum(arr,axis = 0)

np.float64(6.0)

In [ ]:
# Calculate the sum of elements along axis 1 (rows) for the array 'arr'
# Note: This likely refers to a previous 'arr' which was a 2D array.
np.sum(arr,axis = 1)

array([ 15,  40,  65,  90, 115, 140])

In [ ]:
# Calculate the mean of the elements in the array 'arr'
# Note: This likely refers to a previous 'arr' which was a 2D array.
arr.mean()

np.float64(3.0)

In [ ]:
# Calculate the standard deviation of the elements in the array 'arr'
# Note: This likely refers to a previous 'arr' which was a 2D array.
arr.std()

np.float64(2.0)

In [ ]:
# Get the index of the maximum value in the flattened array 'arr'
# Note: This likely refers to a previous 'arr' which was a 2D array.
arr.argmax()

np.int64(1)

In [ ]:
# Get the index of the minimum value in the flattened array 'arr'
# Note: This likely refers to a previous 'arr' which was a 2D array.
arr.argmin()

np.int64(0)

### Reshape and resizing

In [ ]:
# Create a NumPy array with a range of values from 1 to 30
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# Reshape the array 'arr' into a 6x5 matrix
arr = arr.reshape(6,5)

In [ ]:
# Display the reshaped array
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])