<a href="https://colab.research.google.com/github/swopnimghimire-123123/Data_Analysis_-_Visualization/blob/main/02_Array_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy indexing and slicing of vectors

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[4]

np.int64(15)

In [ ]:
arr[1:5]

array([12, 13, 14, 15])

In [ ]:
arr[:5]

array([11, 12, 13, 14, 15])

In [ ]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3::2]

array([14, 16, 18, 20])

In [ ]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

### Numpy Indexing and slicing of matrix

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[0,4]

np.int64(5)

In [ ]:
arr[5]

array([26, 27, 28, 29, 30])

In [ ]:
arr[5,3]

np.int64(29)

In [ ]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [ ]:
slice = arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
print(arr)
print(arr[:,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[ 3  8 13 18 23 28]


### Boolean Indexing

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# Create a boolean index that is True for even numbers
bool_index = arr % 2 == 0

# Use the boolean index to select even numbers from the array
arr = arr[bool_index]

In [ ]:
# Display the array containing only even numbers
arr

array([12, 14, 16, 18, 20])