<a href="https://colab.research.google.com/github/swopnimghimire-123123/Data_Analysis_-_Visualization/blob/main/04_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy Exercises

In [ ]:
# Valid sudoku

import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
b = np.sum(s, axis = 1)
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
b = np.sum(s, axis = 1)
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
b = np.sum(s, axis = 1)
for i in b:
    if i == 45:
        print("sudoku valid")
    else:
        print("sudoku is invalid")

sudoku valid
sudoku valid
sudoku valid
sudoku valid
sudoku valid
sudoku valid
sudoku valid
sudoku valid
sudoku valid


In [ ]:
c = np.sum(s, axis = 0)
for i in b:
    if i == 45:
        print("sudoku valid")
    else:
        print("sudoku is invalid")

sudoku valid
sudoku valid
sudoku valid
sudoku valid
sudoku valid
sudoku valid
sudoku valid
sudoku valid
sudoku valid


In [ ]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [ ]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n = s[i:i+3,j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


### General Questions

In [ ]:
import numpy as np

# columns : [Age, Math Marks, Science Marks]
data = np.array(([18,56,98],
                 [10,89,78],
                 [15,66,78],
                 [10,98,98],
                 [15,66,78],
                 [18,56,35]
                 ))

In [ ]:
# Get the shape of the matrix
data.shape

(6, 3)

In [ ]:
# Find the average of the first column
np.mean(data[:,0])

np.float64(14.333333333333334)

In [ ]:
# Extract math marks of all students
data[:,1]

array([56, 89, 66, 98, 66, 56])

In [ ]:
# Find tha maximum science marks
np.max(data[:,2])

np.int64(98)

In [ ]:
# Get details of the student who scored more than 90 marks in maths
data[data[:,1] > 90]

array([[10, 98, 98]])

In [ ]:
# Increase math marks of all the students b 5
data[:,1] = data[:,1] + 5
data

array([[ 18,  61,  98],
       [ 10,  94,  78],
       [ 15,  71,  78],
       [ 10, 103,  98],
       [ 15,  71,  78],
       [ 18,  61,  35]])

In [ ]:
# print how many students are younger than 19
print(data[data[:,0] < 19].shape[0])
print(data[data[:,0] < 19])

6
[[ 18  61  98]
 [ 10  94  78]
 [ 15  71  78]
 [ 10 103  98]
 [ 15  71  78]
 [ 18  61  35]]


In [ ]:
# Calculate the average marks of each subject
np.mean(data[:,1:],axis = 0)

array([76.83333333, 77.5       ])

In [ ]:
# Get data of students who have scored atleast 80 in both subject
math_condition = data[:, 1] >= 80
science_condition = data[:, 2] >= 80
display(data[math_condition & science_condition])

array([[ 10, 103,  98]])

In [ ]:
# Replace all science marks < 75 with 0
data[:,2][data[:,2] < 75] = 0
print(data)

[[ 18  61  98]
 [ 10  94  78]
 [ 15  71  78]
 [ 10 103  98]
 [ 15  71  78]
 [ 18  61   0]]
